//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.datasus.org/", ConfigurationName="ServiceReference.ServicoSolicitacaoWS")]
    public interface ServicoSolicitacaoWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ItemPesquisaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MedicamentoDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmarRecebimentoReturn")]
        System.Threading.Tasks.Task<ServiceReference.ConfirmacaoRecebimentoDTO> confirmarRecebimentoAsync(ServiceReference.RecebimentoDTO in0, ServiceReference.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ItemPesquisaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MedicamentoDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pesquisarAutorizacoesReturn")]
        System.Threading.Tasks.Task<ServiceReference.RetornoPesquisaDTO> pesquisarAutorizacoesAsync(ServiceReference.PesquisaDTO in0, ServiceReference.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ItemPesquisaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MedicamentoDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="executarSolicitacaoReturn")]
        System.Threading.Tasks.Task<ServiceReference.AutorizacaoDTO> executarSolicitacaoAsync(ServiceReference.SolicitacaoDTO in0, ServiceReference.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ItemPesquisaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MedicamentoDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="executarEstornoReturn")]
        System.Threading.Tasks.Task<ServiceReference.ConfirmacaoEstornoDTO> executarEstornoAsync(ServiceReference.EstornoDTO in0, ServiceReference.UsuarioFarmaciaDTO in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ItemPesquisaDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsuarioDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MedicamentoDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmarAutorizacaoReturn")]
        System.Threading.Tasks.Task<ServiceReference.ConfirmacaoAutorizacaoDTO> confirmarAutorizacaoAsync(ServiceReference.ConfirmacaoDTO in0, ServiceReference.UsuarioFarmaciaDTO in1);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class RecebimentoDTO
    {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string nuAutorizacaoField;
        
        private string nuCupomFiscalField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO
        {
            get
            {
                return this.arrMedicamentoDTOField;
            }
            set
            {
                this.arrMedicamentoDTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao
        {
            get
            {
                return this.nuAutorizacaoField;
            }
            set
            {
                this.nuAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCupomFiscal
        {
            get
            {
                return this.nuCupomFiscalField;
            }
            set
            {
                this.nuCupomFiscalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class MedicamentoDTO
    {
        
        private string coCodigoBarraField;
        
        private string dsUnidApresentacaoField;
        
        private string inAutorizacaoEstornoField;
        
        private string inAutorizacaoMedicamentoField;
        
        private double qtAutorizadaField;
        
        private double qtDevolvidaField;
        
        private double qtEstornadaField;
        
        private double qtPrescritaField;
        
        private double qtSolicitadaField;
        
        private string statusTransacaoField;
        
        private double vlPrecoSubsidiadoMSField;
        
        private double vlPrecoSubsidiadoPacienteField;
        
        private double vlPrecoSubsidiadoPacientePosEstornoField;
        
        private double vlPrecoVendaField;
        
        private double vlrSubsidiadoMSPosEstornoField;
        
        private double vlrTotalVendaPosEstornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coCodigoBarra
        {
            get
            {
                return this.coCodigoBarraField;
            }
            set
            {
                this.coCodigoBarraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dsUnidApresentacao
        {
            get
            {
                return this.dsUnidApresentacaoField;
            }
            set
            {
                this.dsUnidApresentacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inAutorizacaoEstorno
        {
            get
            {
                return this.inAutorizacaoEstornoField;
            }
            set
            {
                this.inAutorizacaoEstornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inAutorizacaoMedicamento
        {
            get
            {
                return this.inAutorizacaoMedicamentoField;
            }
            set
            {
                this.inAutorizacaoMedicamentoField = value;
            }
        }
        
        /// <remarks/>
        public double qtAutorizada
        {
            get
            {
                return this.qtAutorizadaField;
            }
            set
            {
                this.qtAutorizadaField = value;
            }
        }
        
        /// <remarks/>
        public double qtDevolvida
        {
            get
            {
                return this.qtDevolvidaField;
            }
            set
            {
                this.qtDevolvidaField = value;
            }
        }
        
        /// <remarks/>
        public double qtEstornada
        {
            get
            {
                return this.qtEstornadaField;
            }
            set
            {
                this.qtEstornadaField = value;
            }
        }
        
        /// <remarks/>
        public double qtPrescrita
        {
            get
            {
                return this.qtPrescritaField;
            }
            set
            {
                this.qtPrescritaField = value;
            }
        }
        
        /// <remarks/>
        public double qtSolicitada
        {
            get
            {
                return this.qtSolicitadaField;
            }
            set
            {
                this.qtSolicitadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusTransacao
        {
            get
            {
                return this.statusTransacaoField;
            }
            set
            {
                this.statusTransacaoField = value;
            }
        }
        
        /// <remarks/>
        public double vlPrecoSubsidiadoMS
        {
            get
            {
                return this.vlPrecoSubsidiadoMSField;
            }
            set
            {
                this.vlPrecoSubsidiadoMSField = value;
            }
        }
        
        /// <remarks/>
        public double vlPrecoSubsidiadoPaciente
        {
            get
            {
                return this.vlPrecoSubsidiadoPacienteField;
            }
            set
            {
                this.vlPrecoSubsidiadoPacienteField = value;
            }
        }
        
        /// <remarks/>
        public double vlPrecoSubsidiadoPacientePosEstorno
        {
            get
            {
                return this.vlPrecoSubsidiadoPacientePosEstornoField;
            }
            set
            {
                this.vlPrecoSubsidiadoPacientePosEstornoField = value;
            }
        }
        
        /// <remarks/>
        public double vlPrecoVenda
        {
            get
            {
                return this.vlPrecoVendaField;
            }
            set
            {
                this.vlPrecoVendaField = value;
            }
        }
        
        /// <remarks/>
        public double vlrSubsidiadoMSPosEstorno
        {
            get
            {
                return this.vlrSubsidiadoMSPosEstornoField;
            }
            set
            {
                this.vlrSubsidiadoMSPosEstornoField = value;
            }
        }
        
        /// <remarks/>
        public double vlrTotalVendaPosEstorno
        {
            get
            {
                return this.vlrTotalVendaPosEstornoField;
            }
            set
            {
                this.vlrTotalVendaPosEstornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class ConfirmacaoAutorizacaoDTO
    {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string coSolicitacaoFarmaciaField;
        
        private string descMensagemErroField;
        
        private string inAutorizacaoSolicitacaoField;
        
        private string noPessoaField;
        
        private string nuAutorizacaoField;
        
        private string nuCupomFiscalField;
        
        private string statusConfirmacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO
        {
            get
            {
                return this.arrMedicamentoDTOField;
            }
            set
            {
                this.arrMedicamentoDTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coSolicitacaoFarmacia
        {
            get
            {
                return this.coSolicitacaoFarmaciaField;
            }
            set
            {
                this.coSolicitacaoFarmaciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descMensagemErro
        {
            get
            {
                return this.descMensagemErroField;
            }
            set
            {
                this.descMensagemErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inAutorizacaoSolicitacao
        {
            get
            {
                return this.inAutorizacaoSolicitacaoField;
            }
            set
            {
                this.inAutorizacaoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string noPessoa
        {
            get
            {
                return this.noPessoaField;
            }
            set
            {
                this.noPessoaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao
        {
            get
            {
                return this.nuAutorizacaoField;
            }
            set
            {
                this.nuAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCupomFiscal
        {
            get
            {
                return this.nuCupomFiscalField;
            }
            set
            {
                this.nuCupomFiscalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusConfirmacao
        {
            get
            {
                return this.statusConfirmacaoField;
            }
            set
            {
                this.statusConfirmacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class ConfirmacaoDTO
    {
        
        private string coSolicitacaoFarmaciaField;
        
        private string descMensagemField;
        
        private string nuAutorizacaoField;
        
        private string nuCupomFiscalField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coSolicitacaoFarmacia
        {
            get
            {
                return this.coSolicitacaoFarmaciaField;
            }
            set
            {
                this.coSolicitacaoFarmaciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descMensagem
        {
            get
            {
                return this.descMensagemField;
            }
            set
            {
                this.descMensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao
        {
            get
            {
                return this.nuAutorizacaoField;
            }
            set
            {
                this.nuAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCupomFiscal
        {
            get
            {
                return this.nuCupomFiscalField;
            }
            set
            {
                this.nuCupomFiscalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class ConfirmacaoEstornoDTO
    {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string descMensagemErroField;
        
        private string inSituacaoEstornoField;
        
        private string nuEstornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO
        {
            get
            {
                return this.arrMedicamentoDTOField;
            }
            set
            {
                this.arrMedicamentoDTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descMensagemErro
        {
            get
            {
                return this.descMensagemErroField;
            }
            set
            {
                this.descMensagemErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inSituacaoEstorno
        {
            get
            {
                return this.inSituacaoEstornoField;
            }
            set
            {
                this.inSituacaoEstornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuEstorno
        {
            get
            {
                return this.nuEstornoField;
            }
            set
            {
                this.nuEstornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class EstornoDTO
    {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string nuAutorizacaoField;
        
        private string nuCnpjField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO
        {
            get
            {
                return this.arrMedicamentoDTOField;
            }
            set
            {
                this.arrMedicamentoDTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao
        {
            get
            {
                return this.nuAutorizacaoField;
            }
            set
            {
                this.nuAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpj
        {
            get
            {
                return this.nuCnpjField;
            }
            set
            {
                this.nuCnpjField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class AutorizacaoDTO
    {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string coSolicitacaoFarmaciaField;
        
        private string descMensagemErroField;
        
        private string inAutorizacaoSolicitacaoField;
        
        private string noPessoaField;
        
        private string nuAutorizacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO
        {
            get
            {
                return this.arrMedicamentoDTOField;
            }
            set
            {
                this.arrMedicamentoDTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coSolicitacaoFarmacia
        {
            get
            {
                return this.coSolicitacaoFarmaciaField;
            }
            set
            {
                this.coSolicitacaoFarmaciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descMensagemErro
        {
            get
            {
                return this.descMensagemErroField;
            }
            set
            {
                this.descMensagemErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inAutorizacaoSolicitacao
        {
            get
            {
                return this.inAutorizacaoSolicitacaoField;
            }
            set
            {
                this.inAutorizacaoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string noPessoa
        {
            get
            {
                return this.noPessoaField;
            }
            set
            {
                this.noPessoaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao
        {
            get
            {
                return this.nuAutorizacaoField;
            }
            set
            {
                this.nuAutorizacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class SolicitacaoDTO
    {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string coSolicitacaoFarmaciaField;
        
        private string dnaEstacaoField;
        
        private System.Nullable<System.DateTime> dtEmissaoReceitaField;
        
        private string dtEmissaoReceitaAsStringField;
        
        private string nuCnpjField;
        
        private string nuCpfField;
        
        private string nuCrmField;
        
        private string sgUfCrmField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO
        {
            get
            {
                return this.arrMedicamentoDTOField;
            }
            set
            {
                this.arrMedicamentoDTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coSolicitacaoFarmacia
        {
            get
            {
                return this.coSolicitacaoFarmaciaField;
            }
            set
            {
                this.coSolicitacaoFarmaciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dnaEstacao
        {
            get
            {
                return this.dnaEstacaoField;
            }
            set
            {
                this.dnaEstacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtEmissaoReceita
        {
            get
            {
                return this.dtEmissaoReceitaField;
            }
            set
            {
                this.dtEmissaoReceitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dtEmissaoReceitaAsString
        {
            get
            {
                return this.dtEmissaoReceitaAsStringField;
            }
            set
            {
                this.dtEmissaoReceitaAsStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpj
        {
            get
            {
                return this.nuCnpjField;
            }
            set
            {
                this.nuCnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCpf
        {
            get
            {
                return this.nuCpfField;
            }
            set
            {
                this.nuCpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCrm
        {
            get
            {
                return this.nuCrmField;
            }
            set
            {
                this.nuCrmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sgUfCrm
        {
            get
            {
                return this.sgUfCrmField;
            }
            set
            {
                this.sgUfCrmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class ItemPesquisaDTO
    {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string coSolicitacaoFarmaciaField;
        
        private System.Nullable<System.DateTime> dtAutorizacaoField;
        
        private System.Nullable<System.DateTime> dtRecebimentoField;
        
        private System.Nullable<System.DateTime> dtSolicitacaoField;
        
        private string nuAutorizacaoField;
        
        private string nuCpfField;
        
        private string nuCrmField;
        
        private string nuCupomFiscalField;
        
        private string sgUfCrmField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO
        {
            get
            {
                return this.arrMedicamentoDTOField;
            }
            set
            {
                this.arrMedicamentoDTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string coSolicitacaoFarmacia
        {
            get
            {
                return this.coSolicitacaoFarmaciaField;
            }
            set
            {
                this.coSolicitacaoFarmaciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtAutorizacao
        {
            get
            {
                return this.dtAutorizacaoField;
            }
            set
            {
                this.dtAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtRecebimento
        {
            get
            {
                return this.dtRecebimentoField;
            }
            set
            {
                this.dtRecebimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtSolicitacao
        {
            get
            {
                return this.dtSolicitacaoField;
            }
            set
            {
                this.dtSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao
        {
            get
            {
                return this.nuAutorizacaoField;
            }
            set
            {
                this.nuAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCpf
        {
            get
            {
                return this.nuCpfField;
            }
            set
            {
                this.nuCpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCrm
        {
            get
            {
                return this.nuCrmField;
            }
            set
            {
                this.nuCrmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCupomFiscal
        {
            get
            {
                return this.nuCupomFiscalField;
            }
            set
            {
                this.nuCupomFiscalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sgUfCrm
        {
            get
            {
                return this.sgUfCrmField;
            }
            set
            {
                this.sgUfCrmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class RetornoPesquisaDTO
    {
        
        private ItemPesquisaDTO[] arrItemPesquisaDTOField;
        
        private string codigoRetornoField;
        
        private System.Nullable<System.DateTime> dataFimField;
        
        private System.Nullable<System.DateTime> dataInicioField;
        
        private string mensagemRetornoField;
        
        private string nuCnpjField;
        
        private string nuCnpjMatrizField;
        
        private int numeroPaginaField;
        
        private int quantidadePaginasField;
        
        private string statusTransacaoField;
        
        private int totalTransacoesField;
        
        private int totalTransacoesPaginaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ItemPesquisaDTO[] arrItemPesquisaDTO
        {
            get
            {
                return this.arrItemPesquisaDTOField;
            }
            set
            {
                this.arrItemPesquisaDTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigoRetorno
        {
            get
            {
                return this.codigoRetornoField;
            }
            set
            {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataFim
        {
            get
            {
                return this.dataFimField;
            }
            set
            {
                this.dataFimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataInicio
        {
            get
            {
                return this.dataInicioField;
            }
            set
            {
                this.dataInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mensagemRetorno
        {
            get
            {
                return this.mensagemRetornoField;
            }
            set
            {
                this.mensagemRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpj
        {
            get
            {
                return this.nuCnpjField;
            }
            set
            {
                this.nuCnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpjMatriz
        {
            get
            {
                return this.nuCnpjMatrizField;
            }
            set
            {
                this.nuCnpjMatrizField = value;
            }
        }
        
        /// <remarks/>
        public int numeroPagina
        {
            get
            {
                return this.numeroPaginaField;
            }
            set
            {
                this.numeroPaginaField = value;
            }
        }
        
        /// <remarks/>
        public int quantidadePaginas
        {
            get
            {
                return this.quantidadePaginasField;
            }
            set
            {
                this.quantidadePaginasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusTransacao
        {
            get
            {
                return this.statusTransacaoField;
            }
            set
            {
                this.statusTransacaoField = value;
            }
        }
        
        /// <remarks/>
        public int totalTransacoes
        {
            get
            {
                return this.totalTransacoesField;
            }
            set
            {
                this.totalTransacoesField = value;
            }
        }
        
        /// <remarks/>
        public int totalTransacoesPagina
        {
            get
            {
                return this.totalTransacoesPaginaField;
            }
            set
            {
                this.totalTransacoesPaginaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class PesquisaDTO
    {
        
        private System.Nullable<System.DateTime> dataFimField;
        
        private System.Nullable<System.DateTime> dataInicioField;
        
        private string nuCnpjField;
        
        private string nuCnpjMatrizField;
        
        private int numeroPaginaField;
        
        private string statusTransacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataFim
        {
            get
            {
                return this.dataFimField;
            }
            set
            {
                this.dataFimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataInicio
        {
            get
            {
                return this.dataInicioField;
            }
            set
            {
                this.dataInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpj
        {
            get
            {
                return this.nuCnpjField;
            }
            set
            {
                this.nuCnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuCnpjMatriz
        {
            get
            {
                return this.nuCnpjMatrizField;
            }
            set
            {
                this.nuCnpjMatrizField = value;
            }
        }
        
        /// <remarks/>
        public int numeroPagina
        {
            get
            {
                return this.numeroPaginaField;
            }
            set
            {
                this.numeroPaginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusTransacao
        {
            get
            {
                return this.statusTransacaoField;
            }
            set
            {
                this.statusTransacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class ConfirmacaoRecebimentoDTO
    {
        
        private MedicamentoDTO[] arrMedicamentoDTOField;
        
        private string codigoRetornoField;
        
        private string cupomVinculadoField;
        
        private string mensagemRetornoField;
        
        private string nuAutorizacaoField;
        
        private string statusRecebimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public MedicamentoDTO[] arrMedicamentoDTO
        {
            get
            {
                return this.arrMedicamentoDTOField;
            }
            set
            {
                this.arrMedicamentoDTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigoRetorno
        {
            get
            {
                return this.codigoRetornoField;
            }
            set
            {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cupomVinculado
        {
            get
            {
                return this.cupomVinculadoField;
            }
            set
            {
                this.cupomVinculadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string mensagemRetorno
        {
            get
            {
                return this.mensagemRetornoField;
            }
            set
            {
                this.mensagemRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nuAutorizacao
        {
            get
            {
                return this.nuAutorizacaoField;
            }
            set
            {
                this.nuAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusRecebimento
        {
            get
            {
                return this.statusRecebimentoField;
            }
            set
            {
                this.statusRecebimentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(UsuarioFarmaciaDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class UsuarioDTO
    {
        
        private string senhaFarmaciaField;
        
        private string senhaVendedorField;
        
        private string usuarioFarmaciaField;
        
        private string usuarioVendedorField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string senhaFarmacia
        {
            get
            {
                return this.senhaFarmaciaField;
            }
            set
            {
                this.senhaFarmaciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string senhaVendedor
        {
            get
            {
                return this.senhaVendedorField;
            }
            set
            {
                this.senhaVendedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string usuarioFarmacia
        {
            get
            {
                return this.usuarioFarmaciaField;
            }
            set
            {
                this.usuarioFarmaciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string usuarioVendedor
        {
            get
            {
                return this.usuarioVendedorField;
            }
            set
            {
                this.usuarioVendedorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://service.datasus.org/")]
    public partial class UsuarioFarmaciaDTO : UsuarioDTO
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface ServicoSolicitacaoWSChannel : ServiceReference.ServicoSolicitacaoWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class ServicoSolicitacaoWSClient : System.ServiceModel.ClientBase<ServiceReference.ServicoSolicitacaoWS>, ServiceReference.ServicoSolicitacaoWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicoSolicitacaoWSClient() : 
                base(ServicoSolicitacaoWSClient.GetDefaultBinding(), ServicoSolicitacaoWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicoSolicitacaoWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoSolicitacaoWSClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicoSolicitacaoWSClient.GetBindingForEndpoint(endpointConfiguration), ServicoSolicitacaoWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoSolicitacaoWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicoSolicitacaoWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoSolicitacaoWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicoSolicitacaoWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicoSolicitacaoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ConfirmacaoRecebimentoDTO> confirmarRecebimentoAsync(ServiceReference.RecebimentoDTO in0, ServiceReference.UsuarioFarmaciaDTO in1)
        {
            return base.Channel.confirmarRecebimentoAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.RetornoPesquisaDTO> pesquisarAutorizacoesAsync(ServiceReference.PesquisaDTO in0, ServiceReference.UsuarioFarmaciaDTO in1)
        {
            return base.Channel.pesquisarAutorizacoesAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AutorizacaoDTO> executarSolicitacaoAsync(ServiceReference.SolicitacaoDTO in0, ServiceReference.UsuarioFarmaciaDTO in1)
        {
            return base.Channel.executarSolicitacaoAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ConfirmacaoEstornoDTO> executarEstornoAsync(ServiceReference.EstornoDTO in0, ServiceReference.UsuarioFarmaciaDTO in1)
        {
            return base.Channel.executarEstornoAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ConfirmacaoAutorizacaoDTO> confirmarAutorizacaoAsync(ServiceReference.ConfirmacaoDTO in0, ServiceReference.UsuarioFarmaciaDTO in1)
        {
            return base.Channel.confirmarAutorizacaoAsync(in0, in1);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicoSolicitacaoWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicoSolicitacaoWS))
            {
                return new System.ServiceModel.EndpointAddress("https://farmaciapopular-autorizador.saude.gov.br/farmaciapopular-autorizador/serv" +
                        "ices/ServicoSolicitacaoWS");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicoSolicitacaoWSClient.GetBindingForEndpoint(EndpointConfiguration.ServicoSolicitacaoWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicoSolicitacaoWSClient.GetEndpointAddress(EndpointConfiguration.ServicoSolicitacaoWS);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicoSolicitacaoWS,
        }
    }
}
